### ISSUE TITLE
VM Live migration fails

### ISSUE THREAD

**Issue by tomcsi** [emc-openstack/vnx-direct-driver#4]
This driver create a storage group same name of hypervisor, but if Openstack try to live migration a vm then get error, because the another hypervisor doesn't see the lun. I would like to request the option, that I set to storage group name instead of storage group per hypervisor.

**Comment by tomcsanyid** [comment]
@xing-yang I have the same issue as well, could this be implemented that it could be set as an option maybe? Thanks.
Basically we want to have multiple hypervisors in the same storage group.

**Comment by xing-yang** [comment]
What version of the VNX direct driver are you using for testing?

**Comment by tomcsi** [comment]
I installed from ubuntu 14.04 python-cinder package, and the VERSION constans in emc_vnx_cli.py is 05.03.05.

**Comment by xing-yang** [comment]
So that is a driver version for Kilo.  I am not aware that storage group name is a problem for live migration.  I'm asking the VNX team to take a look.

**Comment by tomcsi** [comment]
Possible implement to driver that set a common storage group instead of storage group per hypervisor?

**Comment by Tianqi-Tang** [comment]
@Tomcsi, 

Did you find any error in the cinder log and nova log when the live migration failed? Would you please provide the both the logs for Nova and Cinder?
 
Besides, would you please let me know your enviornment configurations:
    1. Is multipath used?
    2. You are using FC or iSCSI?
    3. Version of the Cinder and Nova?

Maybe it is not the storage group issue as the Nova will attach the LUN to the target hypervisor.

Thanks,
Tina

**Comment by tomcsanyid** [comment]
Hi all,

The problem we are having is that by default this driver creates a new storage group (inside of the EMC storage system) per hypervisor. For live migration (HyperV feature) to work multiple hypervisors need to have access to the LUN of the VM, but this isn't the case since they are in different storage groups, and there is no way to access a LUN from a different storage group.
The solution would be to let us specify one single storage group for all hypervisors so everyone can access all LUNs and then live migration would be possible.

Thanks!

2015. szept. 18. dátummal, 4:48 időpontban Tina Tang <notifications@github.com> írta:

**Comment by phenoxim** [comment]
@tomcsanyid 

Are you saying you are not using nova live-migration? You are using hypervisor's live-migration?

**Comment by Tianqi-Tang** [comment]
@tomcsanyid,

Your request is understood, however, we want to verify whether it is required as per our test with Libvirt driver(where KVM is the hypervisor), the live migration is possible with the dirver as it is. So we would like to know your configurations and how do you do the test.  Basically although the storage group is per hypervisors, we can still assign a same LUN to multiple storage groups to make it accessible to multiple hypervisors. 

Could you let me know how do you trigger the live migration?  Using the hypervisor command directly or using the nova live-migration command? 

It would be helpful if you could provide your log files for analysis. 

Thanks,
Tina

**Comment by tomcsi** [comment]
@Tianqi-Tang 

1. Yes
2. iSCSI
3. 2015.1

**Comment by tomcsi** [comment]
@phenoxim It does not work for me to nova live-migration.

**Comment by tomcsi** [comment]
Any new news in issue ?

**Comment by xing-yang** [comment]
I think Tina asked how did you trigger “live migration” but I haven’t seen an answer yet.  Did you run a command from command line?  If so, what is the command?  Did you run it from GUI?  Please specify how you run it and also provide logs if it fails.

**Comment by tomcsanyid** [comment]
Since I'm working together with @tomcsi on this issue let me answer your questions so we can move this issue forward:
We try to perform a simple live migration from Horizon - simply going to Admin -> Instances, selecting an instance and then saying "Live migrate" and choosing the other hypervisor as target.

The error message in the logs are the same (nova-compute.log) on both hypervisors:
```
2015-09-29 17:00:47.331 3924 DEBUG nova.compute.resource_tracker [req-e55effff-e3ba-47be-add7-33c335a703f2 - - - - -] Migration instance not found: Instance 5e8ce432-7792-452c-b966-d427367d0c4d could not be found.
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 422, in _object_dispatch
    return getattr(target, method)(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/nova/objects/base.py", line 163, in wrapper
    result = fn(cls, context, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/nova/objects/instance.py", line 559, in get_by_uuid
    use_slave=use_slave)

  File "/usr/lib/python2.7/dist-packages/nova/db/api.py", line 651, in instance_get_by_uuid
    columns_to_join, use_slave=use_slave)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 233, in wrapper
    return f(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 1744, in instance_get_by_uuid
    columns_to_join=columns_to_join, use_slave=use_slave)

  File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.py", line 1756, in _instance_get_by_uuid
    raise exception.InstanceNotFound(instance_id=uuid)

InstanceNotFound: Instance 5e8ce432-7792-452c-b966-d427367d0c4d could not be found.
```

It is obvious (if I understand the message correctly) that the target hypervisor doesn't see the instance's disk (because they are not in the same storage group) and therefore doesn't allow the live migration to complete.

**Comment by tomcsanyid** [comment]
@Tianqi-Tang if you need anything else let me know, we are ready to give you any help so the issue could be solved soon.

**Comment by peter-wangxu** [comment]
Close it for now, please reopen it once found again.
